### ISSUE TITLE
Smoother Signatures

### ISSUE THREAD

**Issue by MarcGodard** [thomasjbradley/signature-pad#103]
I must say that I like your library so much better than other signature pad libraries (esp jSignature that I was using at first--it preforms badly in IE10+)

The jSignature library has a smoother line however. It smoothes them so they don't look so rough.

I would like to help to add that to this library. @thomasjbradley can you help me with that? Maybe point me in the right direction?

**Comment by eladnova** [comment]
Guys - is the smoothing feature now part of the latest official repo?

**Comment by thomasjbradley** [comment]
@eladnova Nope, unforutnately it is not.
