### ISSUE TITLE
Re sizing the signature pad

### ISSUE THREAD

**Issue by rathnamvemula** [thomasjbradley/signature-pad#109]
I have increased the size of the signature pad by making necessary changes in css files.
It shows fine on UI. But after signing on signature pad, the full signature is not captured on the exported PDF. Please let me know what other changes i need to make in order to capture the full signature. I am doing the signature with in the gray line area itself.

![3-24-2014 10-32-25 am](https://f.cloud.github.com/assets/6290487/2495607/c161160a-b2fc-11e3-8ce8-3f222a072a7d.png)

**Comment by ainsophical** [comment]
I had the same problem with sigpad2image for python conversion of json to png. You will have to resize the blanksig.png and nosig.png files in photoshop/gimp to the canvas size you have marked up in your canvas tag.

**Comment by DarkSDragon** [comment]
Im sorry, unless ive missed where it is in the documentation i cant find the part where it tells me where in the .js file to change the size of the image. Ive searched through all the .js files provided and i cant find any of the var defined in the documentation at all.

Anyone able to point me in the right direction?

**Comment by thomasjbradley** [comment]
@DarkSDragon Here ya go:
https://github.com/thomasjbradley/signature-pad/blob/gh-pages/documentation.md#resizing-the-signature-pad

**Comment by DarkSDragon** [comment]
Thanks for the reply.

I have done that part with the css and the html. Im looking for the area to
change the size of the end image. Unless im missing something i cant seem
to find it. Ive trolled through the js code of both the files supplied and
i cant nail it down.

DSD

**Comment by thomasjbradley** [comment]
@DarkSDragon Change the dimensions from the JSON array? The way I've done it in the past is just multiplied all the coordinates.

**Comment by DarkSDragon** [comment]
Im just having trouble locating the array that controls that in the jason.js file. any hints on the line for it? Sorry this is making me feel so stupid lol.

**Comment by thomasjbradley** [comment]
You can get at it by using the api method: `getSignature()`
https://github.com/thomasjbradley/signature-pad/blob/gh-pages/documentation.md#api-reference

**Comment by DarkSDragon** [comment]
Thanks for your time and patience Thomas i found what i was after and got it working :) i feel like a twit for missing it lol. I will put it here for others so its clear:

After resizing the Canvas size in the HTML and CSS move over to the SignatureToImage.cs file and change the size of the CanvasWidth and CanvasHeight under public SignatureToImage() section as well.

DSD

**Comment by Marwan-Salim** [comment]
Hi Team.

I realize when i increase the canvas pad thenwhen submit only partial signature displayed. Then i found the solution (Alhamdulillah).

When we convert from json to png we need to specify the following options:

require_once 'api/signature-to-image.php';
 
 $json = filter_input(INPUT_POST, 'output', FILTER_UNSAFE_RAW);// From Signature Pad filtered

//the bold part is where u need to specify your width and height, the default is 198-width,55-height
$img = sigJsonToImage($json,**array('imageSize' => array(198,100)**)); // imageSize => array(width, height)

All the best
