### ISSUE TITLE
IE8 Issue

### ISSUE THREAD

**Issue by goldiv028** [thomasjbradley/signature-pad#113]
What is use of  flashcanvas.swf here and i am getting error in IE8 that "  Object doesn't support this property or method" .?

**Comment by shani622** [comment]
Sir! I am currently working with your Electronic Signatures.....
I have a link of my work using your code, Everything is perfect in
Firefox and Google Chrome but it is not taking signatures in IE.....!
I have searched about that on google but i had found nothing helpful!
Here is the link Please check it:
http://taracs.webatu.com/Form3/signUnder19.php

**Comment by shani622** [comment]
And one more thing that the same code that i have uploaded to the server is running perfect on IE with my localhost!!!
It's really weird.......

**Comment by thomasjbradley** [comment]
@shani622 What version of IE is the problem in?

**Comment by shani622** [comment]
In all versions.........
I have checked in 8th and 11th!

**Comment by thomasjbradley** [comment]
I can't seem to figure out exactly what the problem is... my only thought is that there is some HTML missing that's needed. Try copying and pasting the example HTML into place and see if that fixes it.

**Comment by shani622** [comment]
I have checked it again and it is now working in IE 11,
And still not working in IE 8
I have just replaced two files flashcanvas.js and flashcanvas.swf
