### ISSUE TITLE
Canvas width same has parent div resize for device sizes

### ISSUE THREAD

**Issue by Frank004** [thomasjbradley/signature-pad#122]
Hi I have this problem with the canvas, you cant add W100%  to it so what solution for making the canvas width the same has the div.
I need too use the signature in ipad landscape and on devices.

![screen shot 2014-09-05 at 10 57 59 am](https://cloud.githubusercontent.com/assets/7242689/4166711/826756c4-350d-11e4-8288-085e9b66d1d9.png)

![screen shot 2014-09-05 at 11 04 06 am](https://cloud.githubusercontent.com/assets/7242689/4166766/eeed7c7e-350d-11e4-8283-391ac057456d.png)
![screen shot 2014-09-05 at 11 03 56 am](https://cloud.githubusercontent.com/assets/7242689/4166767/ef0d7ac4-350d-11e4-9ad4-768587ad79e0.png)

**Comment by machadoug** [comment]
@Frank004, 
Did you find a solution for this problem?

**Comment by Frank004** [comment]
@machadoug  no :/  I use one size only.

**Comment by machadoug** [comment]
@Frank004, 

thomasjbradley helped me to find a solution.
See post: https://github.com/thomasjbradley/signature-pad/issues/88#issuecomment-104917044
