### ISSUE TITLE
Invalid argument supplied for foreach() in  on line <b>58</b><br />

### ISSUE THREAD

**Issue by noikhongduoc** [thomasjbradley/signature-pad#143]
Hi there,

Here are the snippet of my code, still can't figure why I get that error even those it does generate the image.

$dropOffImg = sigJsonToImage($row[13]);
      echo($row[13] . "<br>");
      imagepng($dropOffImg, "../images/dropOffSignature{$jobNumb}.png");
      imagedestroy($dropOffImg);
      echo($row[14] . "<br>");
      $pickUpImg = sigJsonToImage($row[14]);
      imagepng($pickUpImg, "../images/pickUpSignature{$jobNumb}.png");
      imagedestroy($pickUpImg);

As for the json content is : [{"lx":95,"ly":31,"mx":95,"my":30},{"lx":96,"ly":29,"mx":95,"my":31},{"lx":96,"ly":30,"mx":96,"my":29},{"lx":96,"ly":31,"mx":96,"my":30},{"lx":94,"ly":31,"mx":96,"my":31},{"lx":94,"ly":32,"mx":94,"my":31},{"lx":93,"ly":35,"mx":94,"my":32},{"lx":93,"ly":36,"mx":93,"my":35},{"lx":89,"ly":38,"mx":93,"my":36},{"lx":89,"ly":39,"mx":89,"my":38},{"lx":84,"ly":39,"mx":89,"my":39},{"lx":82,"ly":41,"mx":84,"my":39},{"lx":81,"ly":41,"mx":82,"my":41},{"lx":76,"ly":43,"mx":81,"my":41},{"lx":75,"ly":44,"mx":76,"my":43},{"lx":74,"ly":44,"mx":75,"my":44},{"lx":74,"ly":45,"mx":74,"my":44},{"lx":73,"ly":45,"mx":74,"my":45},{"lx":70,"ly":45,"mx":73,"my":45},{"lx":69,"ly":45,"mx":70,"my":45},{"lx":68,"ly":45,"mx":69,"my":45},{"lx":71,"ly":44,"mx":68,"my":45},{"lx":71,"ly":43,"mx":71,"my":44},{"lx":72,"ly":43,"mx":71,"my":43},{"lx":73,"ly":42,"mx":"

Cheers

**Comment by thomasjbradley** [comment]
Are you getting an error message? What does it say?
