### ISSUE TITLE
When printing with Chrome the signature disappears.

### ISSUE THREAD

**Issue by davidsouza** [thomasjbradley/signature-pad#157]
You can see the signature on the page when loaded on Chrome. But when you go to print the same page in the Print preview window is missing the signature, and print to PDF or printing to paper does not yield a signature.

**Comment by davidsouza** [comment]
![screen shot 2015-06-12 at 1 57 40 pm](https://cloud.githubusercontent.com/assets/1505598/8139765/157d5786-110b-11e5-8843-0b07c3a800db.jpg)

**Comment by davidsouza** [comment]
![screen shot 2015-06-12 at 1 57 54 pm](https://cloud.githubusercontent.com/assets/1505598/8139769/1b15f216-110b-11e5-9450-1456cc38eac6.jpg)

**Comment by davidsouza** [comment]
I have also files a chromium issue here: https://code.google.com/p/chromium/issues/detail?id=500022

**Comment by thomasjbradley** [comment]
Seems like a bug that won’t print the `<canvas>`.
