### ISSUE TITLE
When using this plugin with chrome / firefox the signatures are not drawn on the canvas

### ISSUE THREAD

**Issue by srikanthlavudia** [thomasjbradley/signature-pad#158]
Hi Thomas,
I'm using this plugin for my form submit, a few days back this was working like a charm and now suddenly this plugin has partially stopped working (i.e. it takes more than 10-15 seconds to draw signatures on the canvas), Could you please help as this signature feature is very important as part of my project release.

This behavior has been observed on both chrome & Firefox browsers (Chrome Version :43.0.2357.124 m, Firefox Version: 38.0.5). Any help is much appreciated.

The demo on the website http://thomasjbradley.ca/lab/signature-pad/accept/ is also affected with the same issue (please do a CTRL + F5) and try to draw signature.

Kind Regards,
Srikanth

**Comment by thomasjbradley** [comment]
I'm not seeing any lag in performance in Firefox or Chrome.
Is it possible a browser plugin is causing it?

**Comment by srikanthlavudia** [comment]
Firstly, thank you Thomas for your response.

Seems to be working now, but we haven't changed anything from the coding perspective. We will try to disable any browser plugins that we are using & will let you know if we face any such behavior again.

Kind Regards,
Srikanth
