### ISSUE TITLE
On draw, it validates form automatically

### ISSUE THREAD

**Issue by webmasterkarthi** [thomasjbradley/signature-pad#164]
I have used jquery validate plugin to validate my form. When i click on the space to draw, it automatically validates the form. It doesn't affect any functionalities but it doesn't look good. Somewhere it triggers validate. Please let me know how to get rid off.

**Comment by thomasjbradley** [comment]
Does the jQuery Validate plugin fire when inputs lose focus?

**Comment by webmasterkarthi** [comment]
Yes, it validates input fields when focusout.

**Comment by thomasjbradley** [comment]
Signature pad does some focusing stuff so that could be it, on this line here:
https://github.com/thomasjbradley/signature-pad/blob/gh-pages/jquery.signaturepad.js#L399

Maybe try commenting that out and see if it works.

**Comment by webmasterkarthi** [comment]
Thankyou.. I fixed it by stopping jquery validation on focus out.
