### ISSUE TITLE
Is there a way to not always require a signature

### ISSUE THREAD

**Issue by jaychen2015** [thomasjbradley/signature-pad#168]
I am implementing this for a delivery system.
The user has the option to sign(by drawing the signature) or they can just simply proceed to next step without a signature.
Right now if no signature is signed, this JS give an error "Please sign the document", is there a way to turn this validation off?

**Comment by thomasjbradley** [comment]
Yep, there's an option called `validateFields`, that defaults to `true`. Change it to `false` and it should make the signature pad optional.

**Comment by jaychen2015** [comment]
Thank you. I missed it while going through the documentation.
