### ISSUE TITLE
Validate fields only when Radio Button is checked

### ISSUE THREAD

**Issue by SerNeo** [thomasjbradley/signature-pad#24]
Hello, I need some help

I'm using Signature-Pad in a Form with 2 Radio Buttons for selecting the payment  method: CreditCard and Electronic Check with Signature pad. 
How can I validate Signature Pad value only when it was selected "Electronic Check"?

Or is there any way to destroy the plugin?

I tryied smth like that but its not working.

$(".payment-chek").click(function () { 
if($(this).closest("table").parent().hasClass("altcharge_processing")) {
   $(".sigPad").signaturePad({drawOnly:true});  
} else {
   $.fn.signaturePad.validateFields = false;
}
});

**Comment by ethanclevenger91** [comment]
Of note - playing with `onFormError` only adjusts how errors are displayed - the form still won't submitted because the `validateForm` function still determines the form is invalid. I ended up turning off `validateFields` and manually validating the form when needed:

```
sigApi = $('.sigPad').signaturePad({
	drawOnly:true,
	validateFields:false //I'll do it myself
});
$('form').on('submit', function(e) {
    if(formShouldValidate) {
        var valid = sigApi.validateForm();
        if(valid) return true;
    }
    return false;
});
```
