### ISSUE TITLE
Invalid argument supplied for foreach() 

### ISSUE THREAD

**Issue by Walschk** [thomasjbradley/signature-pad#6]
Hi Bradley,

I'm getting it all wrong...I followed all the steps, somehow I cannot get it to work. I mean the "signature-to-image.php" saves the "signature.png" file but it saves an empty image, just the canvas.

Also I get the following error message, so I'm guessing it has to do with getting that error sorted out then it will work.

"Warning: Invalid argument supplied for foreach() in /data/21/2/10/22/9802851/user/87685857/htdocs//sigpad/signature-to-image.php on line 51"

Thanks for the help. Oh...by the way Signature Pad's awesome!

**Comment by noikhongduoc** [comment]
I get the same error as well, so how did you fix it Walschk?
