### ISSUE TITLE
Multiple Signature Pads in one form

### ISSUE THREAD

**Issue by grex22** [thomasjbradley/signature-pad#69]
I've got a form that requires both a student signature and a parent's signature, to be submitted at the same time. However, calling the signaturePad() method on the form in question only initializes the first signature pad element in the form, leaving the second one as an inactive, blank, canvas element.

Is there a way around this behavior?

**Comment by MRyan89** [comment]
@thomasjbradley 
When I change the height of the canvas I can't get the whole signature, please help me to change the height.
