### ISSUE TITLE
getSignatureImage() not working in IE8

### ISSUE THREAD

**Issue by Jamesking56** [thomasjbradley/signature-pad#75]
Hello,

I can't get getSignatureImage() to work in IE8...

Is this because IE8 falls back to a flash version?

Thanks.

**Comment by velval** [comment]
I know its quite long time ago, but would you mind posting what  you did to have  getSignatureImage() working in IE8 if you still remember? 

I am facing the same issue. The flashcanvas.js fails on this line "this.B.CallFunction" with an "Object doesn't support this property or method". I am using the "Document Mode = 8" to emulate IE8 on internet explorer 11.
