### ISSUE TITLE
Widths and Responsive Width

### ISSUE THREAD

**Issue by PeterKnightDigital** [thomasjbradley/signature-pad#88]
Hi

Is there a simple way to set the canvas to be 100% width?

Tried the suggestion of ammending  .sigPad but where the signature field is part of a much larger form, changing the css width of .sigPad affects the entire form.

.sigPad {
  margin: 0;
  padding: 0;
  width: 200px; /\* Change the width */
}

In my case, I have a large multi-field web form of which the signature is a small part. 

The form is responsive using Bootstrap 3 and I'd like to be able to set the canvas width to scale responsively on various devices.

<canvas class="pad" width="198" height="55"></canvas>
to
<canvas class="pad" width="100%" height="55"></canvas>

However, this causes the width of the form to be approx 100 pixels.

**Comment by machadoug** [comment]
@thomasjbradley ,
Can you please give me a hint on how to accomplish that?
I've tried to remove the canvas.pad `jQuery('.pad').remove();` then adding the canvas again with new dimensions and executed `$('.sigPad').signaturePad();` one more time, however it didn't work correctly.

Thanks for your hard work.

**Comment by thomasjbradley** [comment]
You could probably just target the width and height attributes of the canvas to change its dimensions.
Then, after you've change the dimensions, regenerate the signature.

You shouldn't have to reinitialize signature pad, it should still be okay. Just capture the signature, change the width/height and regenerate the signature.

**Comment by machadoug** [comment]
@thomasjbradley, 
I was able to make it responsible. Thank you very much.

It would be nice if the `lineTop` parameter was a percentage from top, this way it would be perfect for responsive pages.

Any change you can add that feature for the next version?

Thanks in advanced,
~Douglas

**Comment by thomasjbradley** [comment]
Someone else has suggested switching to a `lineBottom` property instead.

**Comment by machadoug** [comment]
@thomasjbradley , `lineBottom` makes more sense.
I have just added a data-linetop-height-ratio = (lineTop / height) attribute to the `canvas`, so when the page resizes I just multiply the `data-linetop-height-ratio` by the new height and I get a proportional height;

Even if you create a lineBottom property it would be great if it was a percentage of the height instead of pixels, so resizing would be even easier;

Best wishes,

**Comment by jpmad4it** [comment]
I was also able to make the canvas responsive, but when you regenerate the signature it is incorrect. The original JSON which is captured is incorrect due to the responsiveness of the canvas element.
